#!/usr/bin/exec-suid --real -- /bin/bash -p

# art from https://emojicombos.com/karate-ascii-art
cat <<END | while read LINE; do echo "$LINE"; sleep 0.1; done

⠀⡠⢲⠢⢄⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⡀⠀⠀
⠸⠤⠾⢥⡤⠀⠉⠂⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡛⠻⣿⡆⠀
⠀⠀⠀⠀⠈⠑⠤⡈⠤⠁⠢⣀⢀⡤⢤⣀⠠⠔⠒⠂⡰⡆⣀⢴⠃⠀
⠀⠀⠀⠀⠀⠀⠀⠈⠂⢔⠂⢀⡘⠽⢋⣰⣡⡊⠆⢈⠀⡁⠀⣸⢢⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢦⢆⢀⡴⢡⡇⢢⠀⠉⢀⠇⠊⠁⠞⠇
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⠀⠀⡇⡸⠉⠉⠀⡄⢄⢨⠄⣤
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⡴⣻⣿⠶⡦⠐⠒⠑⠖⠁⠴⠋
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢴⡿⡟⢯⣼⣠⠇⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡏⣰⠇⠉⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣧⡟⠀⡆⠀WELCOME
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠃⠐⢵⠁⠀THE
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠃⠀⢀⡌⠀TO
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠁⠲⠂⡁⠀DOJO
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠣⠄⠀⠵⠆⠀

You should be running this challenge through the terminal program in the
GUI Desktop... Let's check!
END

echo -n "Checking"
for i in {1..10}
do
	echo -n "."
	sleep 0.1
done
echo -n $'\r'

pid=$$
while [ $pid -ne 0 ]; do
    cmdline=$(cat /proc/$pid/cmdline | tr '\0' ' ')
    case "$cmdline" in
        *"code-server"*) workspace="code"; break ;;
        *"xfce4-terminal"*) workspace="desktop"; break ;;
        *"ssh-entrypoint"*) workspace="ssh"; break ;;
    esac
    if [ -n "$workspace" ]; then
        break
    fi
    pid=$(grep -oP 'PPid:\s*\K\d+' /proc/$pid/status)
done

if [ "$workspace" == "desktop" ]
then
	cat <<END
You are running in the Desktop!

Let's learn to paste from outside of the Desktop! You can paste directly
from your system clipboard using a keyboard shortcut:

1. Copy the secret token from the challenge description.
2. Click inside this terminal.
3. Press Ctrl+Shift+V (Cmd+Shift+V on macOS) to paste the token.
4. Press Enter to submit it!

This is the paste shortcut for the Linux terminal inside the Desktop.
END

	read TOKEN
	read CORRECT </challenge/.secret
	if [ "$TOKEN" == "$CORRECT" ]
	then
		echo -n "CORRECT! Your flag: "
		cat /flag
	else
		echo "Incorrect. Please try again!"
	fi
else
	echo "NOPE! Run this challenge from the Desktop (rather than VSCode or SSH)!"
fi
